version: 2.1
orbs:
  testutils: lruzicki/testutils@v1.0.3
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - testutils/test-config

workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: govstack-working-group/testutils
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
